version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3-stretch-browsers

    working_directory: ~/repo

    steps:
      - checkout
      - run: cd source
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "source/package-lock.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "source/package-lock.json" }}

      - run: npm run test
      - run: npm run e2e
      - run: npm run build-prod
      - run: cd ..
      - run: cp -r source/dist/portfolio/ .
      - run: git add .
      - run: git config user.email "hugo.marello@gmail.com"
      - run: git config user.name "hugo-marello"
      - run: git commit -m"[skip ci] New version published"
      - run: git push
