version: 2
jobs:

  checkout_code:
    docker:
      - image: circleci/node:10.16.3-stretch-browsers
    working_directory: ~/repo
    steps:
      - checkout

  install-dependencies:
    docker:
      - image: circleci/node:10.16.3-stretch-browsers
    working_directory: ~/repo/source
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

  build:
    docker:
      - image: circleci/node:10.16.3-stretch-browsers
    working_directory: ~/repo/source
    steps:
      - run: npm run build-prod

  unit-test:
    docker:
      - image: circleci/node:10.16.3-stretch-browsers
    working_directory: ~/repo/source
    steps:
      - run: npm run test  

  e2e-test:
    docker:
      - image: circleci/node:10.16.3-stretch-browsers
    working_directory: ~/repo/source
    steps:
      - run: npm run e2e  

  deploy:
    docker:
      - image: circleci/node:10.16.3-stretch-browsers
    working_directory: ~/repo
    steps:
      - run: cp -r source/dist/portfolio/ .
      - run: git add .
      - run: git config user.email "hugo.marello@gmail.com"
      - run: git config user.name "hugo-marello"
      - run: git commit -m"[skip ci] New version published"
      - run: git push

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout_code
      - install-dependencies:
          requires:
            - checkout_code
      - build:
          requires:
            - install-dependencies
      - unit-test:
          requires:
            - install-dependencies
      - e2e-test:
          requires:
            - install-dependencies
      - deploy:
          requires:
            - build
            - unit-test
            - e2e-test
