version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3-stretch-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: unit-test
          command: 'npm run test'
      - run:
          name: interface-test
          command: 'npm run e2e'
      - store_artifacts:
          path: test-results.xml
          prefix: tests
